replicaCount:

image:
  repository: ""
  tag: ""
  pullPolicy: ""

env:
  DOLI_DB_HOST: ""
  DOLI_DB_HOST_PORT: ""
  DOLI_DB_NAME: ""
  DOLI_DB_USER: ""
  DOLI_ADMIN_LOGIN: ""
  DOLI_ADMIN_PASSWORD: ""

service:
  type: ""
  port:
  nodePort:

mariadb:
  auth:
    existingSecret: ""
    rootPassword: ""
    password: ""
    database: ""
    username: ""

  primary:
    containerPorts:
      mysql: ""
    persistence:
      enabled:
      accessModes:
        - ""
      size: ""

resources:
  limits:
    memory: ""
    cpu: ""
  requests:
    memory: ""
    cpu: ""

pvc:
  accessMode: ""
  storage: ""

ingress:
  enabled:
  class: ""
  sslRedirect: ""
  sslRedirectCode: ""
  forwardedFor: ""
  host: ""
