apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dolibarr.fullname" . }}
  labels:
    app: {{ include "dolibarr.name" . }}
    chart: {{ include "dolibarr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "8Gi" }}
